### ISSUE TITLE
Feature request: create .deb package

### ISSUE THREAD

**Issue by Scifire** [OCSInventory-NG/Packager-for-Unix#1]
Hey,

it would be cool if this packager could also create a deb package which could easily deployed via tools like puppet, ansible or aptly

Thanks,

**Comment by gillesdubois** [comment]
Hi,

THere is already a package for RPM but not for debian. It's still in development :)
If you have some knowledge on deb package creation we would be glad to have some help.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
FYI, i'm closing this issue.
All .deb related package ask need to be done here : https://github.com/OCSInventory-NG/packages

Regards,
Gilles Dubois.

**Comment by Scifire** [comment]
@gillesdubois thanks for answering. We used debuild to compile the package, but unfortunately that´s all i have on experience with package creation...
