### ISSUE TITLE
Mac OS Big Sur - Deflating problem

### ISSUE THREAD

**Issue by souwill** [OCSInventory-NG/Packager-for-Unix#14]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Mac OS Big Sur

### OCS Inventory informations
Packager version : 2.6

### Problem's description
*Describe your problem here*
**Deflating problem** into log /var/log/ocsng.log

**Comment by Lea9250** [comment]
Hi @souwill, could you confirm which agent version you are using ? If not already, you might want to try with OCS agent version 2.8 and see if the error still persists
Regards, 
Léa

**Comment by souwill** [comment]
Dears.

The version 2.8 not found in website.

Pic down

![Screen Shot 2021-03-30 at 11 50 43](https://user-images.githubusercontent.com/12651822/113009689-8e8cc980-914e-11eb-9260-178fd4463e65.png)

**Comment by souwill** [comment]
Dears.

Sorry dears

I found the link of version 2.8 now

https://github.com/OCSInventory-NG/UnixAgent/releases/download/v2.8.0-MAC/Ocsinventory-Unix-Agent-2.8.0-MAC.tar.gz

If have problem with this version, I will return the contact! 

Best Regards!

**Comment by souwill** [comment]
Dears,

II made I setup of system on version 2.8 but the log file show the follow error.
```

[Tue Mar 30 21:25:11 2021][error] Deflating problem
[Tue Mar 30 21:28:45 2021][error] Deflating problem

cat /etc/ocsinventory-agent/ocsinventory-agent.cfg
server=http://url_of_server (require vpn connect)
logfile=/var/log/ocsng.log
debug=0
lazy=0
ssl=0

```

Operation System : Mac OS Big Sur - 11.2.3 (20D91)

Please help-me dears!

Thanks!

**Comment by souwill** [comment]
Dears

At here, another computer have the Catalina, the ocsinventory is ok, after this was upgrade to Big Sur, it continues function normality.
But if I make the deploy (version 2.8) In um Macbook directly on Big Sur, show the message of error that I passed.

- Deflating problem

Best  Regards!

**Comment by Lea9250** [comment]
Hi, 
Your error might be related to missing modules, could you check that the perl modules required by the agent have been installed ? These are listed in the agent README file

**Comment by souwill** [comment]
Hi Lea!

I read all documentation and Readme file, install all modules perl but not funcion. 

[Sat Apr  3 02:35:42 2021][error] Deflating problem

Any light is valid, thanks for support

**Comment by Lea9250** [comment]
Hi @souwill,
Thanks for your feedback, we'll take a closer look at this and keep you updated when a solution is found.

Regards, 
Léa

**Comment by souwill** [comment]
Dears 

I wait for news !!!

Best Regards!

**Comment by souwill** [comment]
Hi! 

Any Answer?

O_o

**Comment by Lea9250** [comment]
Hi @souwill,
I have been trying to reproduce the problem you are experiencing but 2.8 agent seems to work properly with Big Sur (11.2.3) on our side, whether after upgrading from Catalina or installing it from scratch. I have noticed your debug wasn't set to 1 in the agent's config file, could you try and change that ? Then see if anything new shows up in the agent's log. 
Thanks for your patience,
Léa

**Comment by souwill** [comment]
Dear Lea

I will recording a video and will uploaded for you in soon!

Best regards!

Thanks for attention of alls!!!!

**Comment by souwill** [comment]
Dears! (TEAM SUPPORT AND DEVs - OCS INVENTORY). About my issue now:

Issue solved! , the real problem was on server, when he was update,  the file that has the password was overwritten and then no computer synchronized with the server. we updated the password in the server file and it worked correctly! Many Thanks for the support OCS Inventory TEAM SUPPORT and DEVS!

----

@Stresscuk 

I am using version 2.6 for big sur and it works correctly!
https://github.com/OCSInventory-NG/UnixAgent/releases/download/v2.6.0-MAC/Ocsinventory_Agent_MacOS-2.6.0.pkg.zip

**Comment by souwill** [comment]
To admin:

Please close this issue! 

@Stresscuk Case have any problem please open a new request!

Best regards!

**Comment by Lea9250** [comment]
Hi @souwill,
Glad to know you solved this :) I'll close this issue now.

To @Stresscuk, you can find the Unix agent release here, including mac ones : https://github.com/OCSInventory-NG/UnixAgent/releases
As far as I know of, Big Sur and OCS seem to work well. Please open an issue on the Unix repo if needed. 

Regards,
Léa
