### ISSUE TITLE
Can't locate IO/Socket/SSL.pm

### ISSUE THREAD

**Issue by nnn-dev** [OCSInventory-NG/Packager-for-Unix#8]
### General informations
Operating system : Debian 9

### OCS Inventory informations
Packager version : master

### Problem's description
The agent is packaged but is not usable.
When I launch /opt/ocsinventory/ocsinventory-agent --basevardir=/opt/ocsinventory/var/lib/ocsinventory-agent -s http://xxx --lazy , I have this error
```

Failed to load Ocsinventory::Agent, Can't locate IO/Socket/SSL.pm in @INC (you may need to install the IO::Socket::SSL module) (@INC contains: /opt/ocsinventory/perl/lib/site_perl/5.26.1/x86_64-linux /opt/ocsinventory/perl/lib/site_perl/5.26.1 /opt/ocsinventory/perl/lib/5.26.1/x86_64-linux /opt/ocsinventory/perl/lib/5.26.1) at /opt/ocsinventory/perl/lib/5.26.1/Ocsinventory/Agent/Network.pm line 7.
BEGIN failed--compilation aborted at /opt/ocsinventory/perl/lib/5.26.1/Ocsinventory/Agent/Network.pm line 7.
Compilation failed in require at /opt/ocsinventory/perl/lib/5.26.1/Ocsinventory/Agent.pm line 33.
BEGIN failed--compilation aborted at /opt/ocsinventory/perl/lib/5.26.1/Ocsinventory/Agent.pm line 33.
Compilation failed in require at (eval 1) line 1.
BEGIN failed--compilation aborted at (eval 1) line 1.

you can run the agent directly for its source directory with --devlib
```

For information, I don't use SSLon config file. It is indicated export OCS_SSL_ENABLED=0
Perhaps some perl modules are missing in the package ?

**Comment by fbomj** [comment]
Hi,
IO::Socket::SSL module is missing. We correct the packager and will release a new version.
Regards
Frank

**Comment by Louis63000** [comment]
Hello,

Do you know when will the next release come out ? I've the same problem like nnn-dev and I need packager to deploy on 15 000 assets :/

Thx a lot.
